# Copyright 2020 Adam Chalkley
#
# https:#github.com/atc0005/bridge
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

# https://github.com/taskctl/taskctl
# https://github.com/taskctl/taskctl/blob/master/docs/example.yaml

pipelines:
  pipeline1:
    - task: task1

    - name: some-stage-name
      task: task2
      depends_on: task1
      allow_failure: true

    - task: task3
      depends_on: task1 # task2 and task3 will run in parallel when task1 finished

    - task: task4
      depends_on: [task1, some-stage-name]
      env:
        VAR_NAME: VAR_VALUE # overrides task env

tasks:
  task1:
    context: local # optional. "local" is context by default
    description: "Optional description for task1"
    command:
      - echo ${ARGS} # ARGS is populated by arguments passed to task. eg. taskctl run task task1 -- arg1 arg2
      - echo "My name is task1"
      - echo ${VAR_NAME_1} - ${VAR_NAME_2}
      - pwd
    env:
      VAR_NAME: VAR_VALUE
    variations:
      - VAR_NAME_1: VARIATION_1
        VAR_NAME_2: VARIATION_1
      - VAR_NAME_1: VARIATION_2
        VAR_NAME_2: VARIATION_2
    dir: /task/working/dir # current directory by default
    timeout: 10s
    before: mkdir some-dir
    after: rm -rf some-dir

  task2:
    context: docker-context-name
    command:
      - echo "Hello from container"
    env:
      VAR_NAME: VAR_VALUE

  task3:
    context: docker-compose-context-name # local is default context
    command:
      - echo "Hello from container created by docker-compose"
    env:
      VAR_NAME: VAR_VALUE

  task4:
    context: kubectl
    command:
      - echo "I'm task4"
      - env
      - uname -a

  task-to-be-triggered-by-watcher:
    command:
      - echo ${EVENT_NAME} ${EVENT_PATH}

  task-with-variations:
    command:
      - GOOS=${GOOS} GOARCH=amd64 go build -o bin/binary_${GOOS} ./...
    variations:
      - GOOS: linux
      - GOOS: darwin
      - GOOS: windows

  test-watch-task:
    command:
      - echo TASK1 $EVENT_NAME $EVENT_PATH

  test-watch-task-2:
    command:
      - echo TASK1 $EVENT_NAME $EVENT_PATH

watchers:
  watcher1:
    watch: ["README.*", "pkg/**/*.go"]
    events: [create, write, remove, rename, chmod]
    task: task1

  test-watcher:
    events: ["write", "rename"]
    watch: ["docker-compose.yaml"]
    task: test-watch-task

  test-watcher-2:
    events: ["write", "rename", "create"]
    watch: ["*.yaml"]
    task: test-watch-task-2

  test-watcher-3:
    events: ["write", "rename", "create"]
    watch: ["*.md", "internal/**/*.go"]
    exclude: "LICENSE.md"
    task: test-watch-task-2

contexts:
  local: # will be created automatically if not set
    type: local
    executable:
      bin: /bin/sh
      args:
        - -c
    env:
      VAR_NAME: VAR_VALUE
    before: echo "SOME COMMAND TO RUN BEFORE EVERY TASK"
    after: echo "SOME COMMAND TO RUN WHEN TASK FINISHED SUCCESSFULLY"

  docker-context-name:
    type: container
    container:
      provider: docker
      image: alpine:latest
      options:
        - -v /folder:/folder
      exec: false
      env:
        VAR_NAME: VAR_VALUE
    env:
      VAR_NAME: VAR_VALUE # eg. "DOCKER_HOST"
    before: echo "SOME COMMAND TO RUN BEFORE TASK"
    after: echo "SOME COMMAND TO RUN WHEN TASK FINISHED SUCCESSFULLY"

  docker-compose-context-name:
    type: container
    container:
      provider: docker-compose
      name: api
      exec: true
      executable:
        args:
          - --file=docker-compose.yaml
      options:
        - --user=root
      env:
        VAR_NAME: VAR_VALUE
    up: docker-compose up -d --build --force-recreate api # Executes once before first context usage
    down: docker-compose down api # Executes once when all tasks done
    env:
      VAR_NAME: VAR_VALUE # eg."COMPOSE_FILE"
    before: SOME COMMAND TO RUN BEFORE TASK
    after: SOME COMMAND TO RUN WHEN TASK FINISHED SUCCESSFULLY

  ssh-context-name:
    type: remote
    ssh:
      user: root
      host: some-server
      options:
        - -6
        - -C
    env:
      VAR_NAME: VAR_VALUE # eg. "DOCKER_HOST"
    before: SOME COMMAND TO RUN BEFORE TASK
    after: SOME COMMAND TO RUN WHEN TASK FINISHED SUCCESSFULLY

# Default values for different providers
shell:
  bin: bin
  args: [arg1, arg2]

docker:
  bin: bin
  args: [arg1, arg2]

docker-compose:
  bin: bin
  args: [arg1, arg2]

kubectl:
  bin: bin
  args: [arg1, arg2]

ssh:
  bin: bin
  args: [arg1, arg2]

debug: true # debug enabled by default. To disable run with "--debug=false"
